Une alternative à vueX
sogilis/Blog pull request #166
Opened 2020-08-31 15:09 UTC by Scra3

Proposition de sommaire :

1. Présentation du prolbème.
2. Solution avec VueX.
3. Solution en utilisant les mécanismes de VueJS.
4. Conclusion

2020-08-31 19:58 UTC, JulioJu commented
J'essayais d'ouvrir le fichier en râlant contre GitLab, mais en fait il est vide lol !

2020-09-01 08:37 UTC, Scra3 commented
Oui le fichier était vide. 
L'article va être co-écrit avec JB, c'était pour partager l'idée de sommaire.

2020-09-02 18:27 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ce store permettra d'externaliser la gestion de certains états qui son considérés comme global à l'app.
Première réflexion : je pense que cette intro n'est pas utile.
En effet, les lecteurs qui peuvent comprendre l'alternative a VueX doivent déjà connaître VueX, donc connaître tout ça.

PS : on peut laisser une ligne, histoire d'avoir une intro quand même.

2020-09-02 18:28 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +# Utilise Vue comme alternative à Vuex
J'aimerai bien aller plus loin pour montrer au lecteur que cet article va vraiment lui être utile.
Un truc du genre : "Vous utilisez VueX ? Alors vous avez rater quelque chose.".

2020-09-02 18:31 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +```
Idée : monter un projet (ou 2) avec les 2 solution (histoire de s'assurer que le code qu'on montre fonctionne bien).

2020-09-02 18:34 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +```
Idée : utiliser [Vue.component()](https://fr.vuejs.org/v2/guide/components.html) pour simplifier les extraits de code (permet de mettre plusieurs composants dans le même extrait.

2020-09-02 19:18 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +```
Pour info, c'est exactement ça que l'on fait : https://fr.vuejs.org/v2/guide/state-management.html

2020-09-03 07:04 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ce store permettra d'externaliser la gestion de certains états qui son considérés comme global à l'app.
oui bonne idée, ça me va.

2020-09-03 07:05 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +# Utilise Vue comme alternative à Vuex
Ok, on peut essayer d'être un peu plus taquin :)

2020-09-03 07:17 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +```
Ouai, quasiment.
Plus sérieusement, je pense que l'intérêt de l'article de blog n'est pas vraiment de montrer comment faire (la doc VueJS l'explique bien), mais plutôt de :
- dire que c'est possible (je pense que plein de gens ne connaissent pas la page en question)
- donner tous les avantages de cette solution (ou plutôt les inconvénients de VueX)
- donner un retour d'XP sur un vrai projet. En gros dire que passe très bien la mise a l'échelle.

2020-09-07 12:51 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +* Facilite les tests unitaires car nous avons pas besoin de manipuler VueX.
Tu parles des test des composants Vue ou des test du code qui gère l'état (state, getter, actions, mutations…) ?
Parce que concernant les tests du code qui gère l'état, VueX rend les tests unitaires plus simple dans l'absolu vu qu'on n'a que des fonction pures.

2020-09-07 14:12 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +* Facilite les tests unitaires car nous avons pas besoin de manipuler VueX.
Je parle bien de test qui gère l'état mais dans un composant.
Quand tu utilises VueX, il faut déclarer VueX, importer le store, parfois mocker certaines méthodes alors que dans notre cas on manipule simplement un attribut data.

2020-09-07 14:15 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +* Facilite les tests unitaires car nous avons pas besoin de manipuler VueX.
J'ai rien dit en faite ...

2020-09-07 15:32 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +WIP
Le plugin Vue.js devtools pour debug.

2020-10-08 08:49 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +C'est tout bête, il suffit de profiter du méacnisme de réactivité de Vue pour partager la même source de vérité entre composants, comme décrit dans la documentation [VueJS](https://fr.vuejs.org/v2/gu
s/méacnisme/mécanisme

2020-10-08 08:51 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +TODO : créer un codepen plus réaliste ou montrer une arboresence de fichier d'un vrai projet
j'ai dû mal à comprendre comment on peut illustrer le problème juste on montrant une arboresence. 
Un codepen plus réaliste serait de monter un projet fake ?

2020-10-08 09:23 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +title: Vous utilisez VueX ? Alors vous avez rater quelque chose.
s/rater/raté ?

2020-10-08 09:37 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +TODO : créer un codepen plus réaliste ou montrer une arboresence de fichier d'un vrai projet
Le problème avec codepen (ou les autres), c'est que tout le JS est dans un seul fichier, du coup on ne peux pas trop montrer comme c'est chiant de naviguer entre composant vue, mutateur, store, getter… a chaque fois il faut ouvrir un nouveau fichier.

En gros ce que j'imaginais, c'est ça :

Dans VueX, on a :
```
components/
   ComponentA.vue
store/
   state.js
   mutators/
      users.js
      order.js
      article.js
      price.js
      catalogue.js
      delivery.js
   getters/
      users.js
      order.js
      article.js
      price.js
      catalogue.js
      delivery.js
   actions/
      users.js
      order.js
      article.js
      price.js
      catalogue.js
      delivery.js
```

Sans VueX, on aurait :
```
components/
   ComponentA.vue
services/
   users.js
   order.js
   article.js
   price.js
   catalogue.js
   delivery.js
```

2020-10-08 09:43 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +TODO : créer un codepen plus réaliste ou montrer une arboresence de fichier d'un vrai projet
Oui effectivement avec cette illustration ça saute aux yeux, c'est pas mal !

2020-10-08 10:21 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Qui dit appel backend, dit notamment gestion d'un spinner, et ce, essentiellement pour le composant a l'origine de l'appel (dans le ca général).
spinner ou skeleton ?

2020-10-08 10:22 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Or, avec VueX, pour gérer cela, il est nécessaire de rajouter un booléen dans le store, et ce pour chaque appel backend :anguished: !
Dans notre solution on est aussi obligé de le faire mais dans le booléen est dans le composant, c'est ça ?

2020-10-08 11:40 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Qui dit appel backend, dit notamment gestion d'un spinner, et ce, essentiellement pour le composant a l'origine de l'appel (dans le ca général).
Oui, c'est pas faux. Il y a probablement un terme générique pour tout ça, mais je ne le connais pas 😢.

2020-10-08 11:41 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Or, avec VueX, pour gérer cela, il est nécessaire de rajouter un booléen dans le store, et ce pour chaque appel backend :anguished: !
Oui, c'est ça (et c'est moins chiant a faire que d'aller ouvrir le fichier mutators, puis le fichier action, puis…).

2020-10-09 09:22 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Or, pour faire cela, VueX requiert un peu de boilerplate, comme l'explique la [documentation a ce sujet](https://lmiller1990.github.io/vue-testing-handbook/vuex-in-components.html#using-createlocalvu
On doit aussi le faire si on utilise un plugin avec notre solution. On supprime ?

2020-10-09 09:34 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Or, pour faire cela, VueX requiert un peu de boilerplate, comme l'explique la [documentation a ce sujet](https://lmiller1990.github.io/vue-testing-handbook/vuex-in-components.html#using-createlocalvu
Je pense que c'est intéressant de le garder, dans le sans ou avec VueX, on est obligé de le faire, alors qu'avec notre solution, ça dépend si on utilise un plugin ou pas. Donc ça peut, potentiellement être un avantage.
Mais si on garde le paragraphe, il faudra expliquer ça.

2020-10-12 07:14 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +		state.all = [
`state.All.push(article)`, pour un seul élément je ne ne pense pas que "destruction" soit le plus efficace.

2020-10-12 07:15 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +		state.all = state.all.remove(article => article.id === articleToRemove.id);
la methode `remove` existe pas. C'est filter qui permet de faire ça :)

2020-10-12 12:36 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +		state.all = state.all.remove(article => article.id === articleToRemove.id);
Sorry, je ne suis plus dans le coup…

2020-10-12 15:27 UTC, Scra3 commented
- [ ] Exemple d'ecommerce sans VueX
* [ ] Test sans plugin
* [ ] Test avec plugin
* [ ] Composant avec Plugin
* [ ]  Composant sans Plugin
- [ ] Exemple d'ecommerce avec VueX
* [ ] Test
* [ ] Composant

2020-10-18 12:35 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +C'est tout bête, il suffit de profiter du méacanisme de réactivité de Vue pour partager la même source de vérité entre composants, comme décrit dans la documentation [VueJS](https://fr.vuejs.org/v2/g
méacanisme => mécanisme ;)

2020-10-19 16:23 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +On image bien que ce problème ne se présente pas sans VueX, toujours pour la même raison : simple appel de fonction JS (ex: `ArticlesRepository.unknownAction()`).
On imagine

2020-10-29 11:29 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Note 2 : `this` n'est pas accessible dans les fonctions (ici `getProductsCount()`) appelées dans une propriété calculée d'un composant Vue (cf plus bas). C'est pourquoi, létat (`state`) est déclaré e
létat => l'état

2020-10-29 11:32 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Note 2 : `this` n'est pas accessible dans les fonctions (ici `getProductsCount()`) appelées dans une propriété calculée d'un composant Vue (cf plus bas). C'est pourquoi, létat (`state`) est déclaré e
je'ai pas trop compris.

2020-10-29 12:54 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Note 2 : `this` n'est pas accessible dans les fonctions (ici `getProductsCount()`) appelées dans une propriété calculée d'un composant Vue (cf plus bas). C'est pourquoi, létat (`state`) est déclaré e
Pas grave, ça va sauter avec l'histoire du getter.

2020-10-30 10:32 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +En effet, nous allons voir ici comment adresser le même problème, mais **a la main**, **en plus simple**, y compris sur une vraie application qui part en production !
a la main => à la main

2020-10-30 10:35 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +- **Exposer des fonctions "utilitaires"** (sans notion fonctionnelles) permettant l'accès et la modification de ces états. Cette partie n'est pas a négliger puisque le fonctionnement de Vue impose un
a négliger => à négliger

2020-10-30 10:38 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Note : l'état doit être exposé aux composants Vue afin que ceux-ci puisse observer les changements et se mettre a jour le cas échéant. C'est une contrainte de cette solution, mais il est facile de fa
Cette section on pourrait la mettre après le code `inventory` car dans cette partie du  code qu'on vient se brancher sur le "state"

2020-10-30 10:41 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +* components/
c'est pas le bon exemple ici, on parle de vuex et on donne un exemple sans vuex

2020-10-30 10:42 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +- un modèle a base d'événements pour la modification de l'état
a base => à base

2020-10-30 10:44 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Il y a des applications où cela peut être utile, et beaucoup où ça ne l'est pas du tout. De nombreuses équipes que nous rencontrons utilisant VueX n'utilisent pas cette outil par exemple.
cette => cet

2020-10-30 10:45 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Maintenant on peut se poser la question suivante : "pourquoi VueX est si répandu ?". Et là, le mystère reste entier, donc n'hésitez pas a commenter sur les raisons qui vous ont poussées a utiliser Vu
pourquoi VueX est si répandu ? en bold

2020-10-30 12:52 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +En effet, nous allons voir ici comment adresser le même problème, mais **a la main**, **en plus simple**, y compris sur une vraie application qui part en production !
```suggestion
En effet, nous allons voir ici comment adresser le même problème, mais **à la main**, **en plus simple**, y compris sur une vraie application qui part en production !
```

2020-10-30 14:02 UTC, bdumas1 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Mais ceci n'est qu'indirectement lié a VueX. En effet, comme conseillé dans [un coin de la documentation](https://vuex.vuejs.org/guide/structure.html), lorsque l'application commence à grossir, il pe
```suggestion
Mais ceci n'est qu'indirectement lié a VueX. En effet, comme conseillé dans [un coin de la documentation](https://vuex.vuejs.org/guide/structure.html), lorsque l'application commence à grossir, il peut être préférable de regrouper les état, actions, mutateurs et getters par domaine, grace aux modules, ce qui donne quelque chose comme ceci :
```

2020-11-02 20:00 UTC, JulioJu requested changes
@jibidus @Scra3 

Beaucoup de fautes d'orthographe à corriger.

Humbles propositions syntaxique.

J'ai pas cherché à comprendre le code que vous avez écrit, vu que je ne connais pas Vue.JS

2020-11-02 20:15 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +En effet, nous allons voir ici comment adresser le même problème, mais **à la main**, **en plus simple**, y compris sur une vraie application qui part en production !
Oui, c'est fait exprès (pour éviter les retours a la ligne malheureux). Il n'en faut pas pour toi ?

2020-11-02 20:23 UTC, JulioJu commented on site/content/posts/2020-08-31-vuex-alternative.md
> +En effet, nous allons voir ici comment adresser le même problème, mais **à la main**, **en plus simple**, y compris sur une vraie application qui part en production !
Si, mais j'avais pas vu que y'en avait un. Déso. J'ai mal regardé.

2020-11-02 20:29 UTC, JulioJu commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Voici un exemple concret que nous allons décrire ci-dessous: <https://github.com/sogilis/Blog-vuex_alternative/tree/master>.
Espace insécable à ajouter avant le `:` .

2020-11-02 20:29 UTC, JulioJu commented on site/content/posts/2020-08-31-vuex-alternative.md
> +## Les avantages
Comme au paragraphe suivants ont traite des points positifs de VueX, je serais volontier plus explicite dans ce titre 

`Pourquoi se passer de VueX ?` .

2020-11-02 20:50 UTC, JulioJu requested changes
@jibidus attention tu as commité .DS_Store . Peux-Tu l'enlever ? Voir aussi #207

2020-11-03 07:39 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Lorsque l'on se trompe dans le nom de l'événement (ex: `this.commit('inrcement')`), aucune erreur n'est remontée : pas de linter possible pour détecter l'erreur au plus tôt, et aucune erreur a l'exéc
```suggestion
Lorsque l'on se trompe dans le nom de l'événement (ex: `this.commit('inrcement')`), aucune erreur n'est remontée : pas de linter possible pour détecter l'erreur au plus tôt, et aucune erreur à l'exécution, il ne se passe juste rien.
```

2020-11-03 07:41 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Avec `Vue.js devtools`, il est possible de **suivre les différentes actions qui ont été déclenchées**, les différents état du store… le tout sans aucune ligne de code supplémentaire.
Je ne savais pas.
```suggestion
Avec `Vue.js devtools`, il est possible de **suivre les différentes actions qui ont été déclenchées**, les différents état du store, etc., le tout sans aucune ligne de code supplémentaire.
```

2020-11-03 07:42 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Il y a des applications où cela peut être utile, et beaucoup où ça ne l'est pas du tout. De nombreuses équipes que nous rencontrons utilisant VueX n'utilisent pas cet outil par exemple.
```suggestion
Il y a des applications où cela peut être utile, et beaucoup où ça ne l'est pas du tout. Nous avons constaté parmi les équipes que nous avons rencontrées que la plupart n'utilisent pas cet outil.
```

2020-11-03 07:47 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +VueX impose un cadre, oblige a structurer une partie du code. Ce peut être intéressant dans une équipe où la part de développeurs peu expérimentés est importante.
```suggestion
VueX impose un cadre, force une certaine architecture. ce qui peut aider une équipes peu expérimentées.
```

2020-11-03 07:47 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +A non, en fait, c'est faisable très facilement sans VueX :
```suggestion
Ah non, en fait, c'est faisable très facilement sans VueX :
```

2020-11-03 07:48 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ce qui permet de ne pas importer le `repository` dans chaque composant :
```suggestion
L'avantage est de ne pas importer le `repository` dans chaque composant :
```

2020-11-03 08:02 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Maintenant on peut se poser la question suivante : "**pourquoi VueX est si répandu ?**". Et là, le mystère reste entier, donc n'hésitez pas a commenter sur les raisons qui vous ont poussées a utilise
```suggestion
Une question demeure : pourquoi VueX est-il si répandu ? Nous n'avons su trouver de réponse. Si vous utilisez VueX, donnez-nous les raisons qui vous ont poussées à l'utiliser, nous serions heureux d'en discuter.
```

2020-11-03 08:02 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +## Ce que VueX peut apporter
```suggestion
## Les points positifs de VueX
```

2020-11-03 08:04 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Malgré tout ça, il ne faut pas pour autant rejeter VueX. En effet, certains avantages peuvent être intéressants :
```suggestion
Malgré les nombreux avantages à ne pas utiliser VueX, cette librairie peut dans certains cas s'avérer très intéressante :
```

2020-11-03 08:05 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +title: Vous utilisez VueX ? Alors vous avez raté quelque chose.
```suggestion
title: Vous utilisez VueX ? Alors vous avez raté quelque chose
```

2020-11-03 08:05 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Voila ce que cela peut donner en terme de découpage :
```suggestion
Voilà ce que cela peut donner en terme de découpage :
```

2020-11-03 08:06 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Résultat : en pratique, lorsque l'on veut comprendre un code existant, il faut suivre le déroulé les appels (actions, mutateurs …), ce qui mène a **beaucoup d'indirections**. C'est d'autant plus frus
```suggestion
Résultat : en pratique, lorsque l'on veut comprendre un code existant, il faut suivre le déroulé des appels (actions, mutateurs …), ce qui mène à **beaucoup d'indirections**. C'est d'autant plus frustrant que, généralement, l'opération qu'on veut suivre est assez triviale comme ajouter/modifier/supprimer un élément à une collection.
```

2020-11-03 08:06 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Idem lorsque l'on veut ajouter une nouvelle fonctionnalité, où l'on doit ouvrir le fichier où l'état est stocké pour ajouter un attribut, puis ouvrir le fichier des actions, etc. C'est lourd, et c'es
```suggestion
Idem lorsque l'on veut ajouter une nouvelle fonctionnalité, où l'on doit ouvrir le fichier où l'état est stocké pour ajouter un attribut, puis ouvrir le fichier des actions, etc. C'est lourd, et c'est d'autant plus **sujet à erreur** que ces élements sont directement dépendants et éloignés entre eux.
```

2020-11-03 08:07 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Tout ça pour dire qu'avec VueX, il y a un risque de s'enfermer dans une organisation technique du code qui n'aide pas a la maintenance.
```suggestion
En somme, VueX risque d'enfermer dans une organisation technique du code qui n'aide pas à la maintenance.
```

2020-11-03 08:07 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +On constate aussi que VueX nécessite d'avoir **2 modèles de données** :
```suggestion
VueX nécessite d'avoir **2 modèles de données** :
```

2020-11-03 08:07 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Une autre contrainte de VueX et l'utilisation de **modèle de programmation basée sur les événements**. En effet, [les mutateurs ne sont pas appelés directement](https://vuex.vuejs.org/guide/mutations
```suggestion
Une autre contrainte de VueX est l'utilisation de **modèle de programmation basé sur les événements**. En effet, [les mutateurs ne sont pas appelés directement](https://vuex.vuejs.org/guide/mutations.html#mutations), mais par l'intermédiaire d'événements qui sont publiés :
```

2020-11-03 08:08 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +  2. Vuex va recherche le ou les mutateur(s) associé(s) a cet événement
```suggestion
  2. Vuex va rechercher le ou les mutateur(s) associé(s) a cet événement
```

2020-11-03 08:08 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Encore une fois, ce modèle de programmation a des avantages, mais sont-ils pertinent sur une application front ?
```suggestion
Encore une fois, ce modèle de programmation a des avantages, mais sont-ils pertinents sur une application front ?
```

2020-11-03 08:08 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Toujours est-il que cela a un coût, et notamment au niveau de la navigabilité dans le code. En effet, les éditeurs et autres IDE ne permettent généralement pas naviguer de `this.commit('increment')`
```suggestion
Toujours est-il que cela a un coût, et notamment au niveau de la navigabilité dans le code. En effet, les éditeurs et autres IDE ne permettent généralement pas de naviguer de `this.commit('increment')` vers les mutateurs associés.
```

2020-11-03 08:10 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ensuite, nous avons cherché a comparer avec le plus d'objectivité possible les 2 solutions. Si l'objectif est atteint, nous pouvons voir un **net avantage en faveur d'une solution sans VueX**, sauf p
Oui, c'est vrai que ça fait très scolaire. Je voulais aussi éviter la forme affirmative/péremptoire. Mais on doit pouvoir trouver mieux que ce qui est fait.

2020-11-03 08:15 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ensuite, nous avons cherché a comparer avec le plus d'objectivité possible les 2 solutions. Si l'objectif est atteint, nous pouvons voir un **net avantage en faveur d'une solution sans VueX**, sauf p
Que pensez-vous de cela ?
```suggestion
Ainsi, en comparant en détail les 2 solutions, la solution sans VueX semble posséder plus d'atouts (simplicité, architecture ouverte…).
```

2020-11-03 08:17 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Voici un exemple concret que nous allons décrire ci-dessous: <https://github.com/sogilis/Blog-vuex_alternative/tree/master>.
```suggestion
Voici un exemple concret que nous allons décrire ci-dessous : <https://github.com/sogilis/Blog-vuex_alternative/tree/master>.
```

2020-11-03 08:17 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +### Aide au débogage avec [Vue.js devtools](https://github.com/vuejs/vue-devtools)
Fixed

2020-11-03 08:19 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +date: 2020-10-08
A faire lorsqu'on saura quand l'article sera publié.

2020-11-03 09:08 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +- **Exposer des fonctions "utilitaires"** (sans notion fonctionnelles) permettant l'accès et la modification de ces états. Cette partie n'est pas à négliger puisque le fonctionnement de Vue impose un
Je propose une note de bas de page, histoire de ne pas polluer le corps du contenu.

2020-11-03 09:09 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Avec [Vue.js devtools](https://github.com/vuejs/vue-devtools), il est possible de **suivre les différentes actions qui ont été déclenchées**, les différents état du store… le tout sans aucune ligne d
```suggestion
Avec [Vue.js devtools](https://github.com/vuejs/vue-devtools), il est possible de **suivre les différentes actions qui ont été déclenchées**, les différents état du store, etc., le tout sans aucune ligne de code supplémentaire.
```
😉 @JulioJu

2020-11-03 09:16 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Il y a des applications où cela peut être utile, et beaucoup où ça ne l'est pas du tout. De nombreuses équipes que nous rencontrons utilisant VueX n'utilisent pas cet outil par exemple.
C'est vrai qu'on a essayé d'être le plus objectif possible jusque là, donc pourquoi ne pas montrer que ce point ne l'est pas.

2020-11-03 09:29 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ensuite, nous avons cherché a comparer avec le plus d'objectivité possible les 2 solutions. Si l'objectif est atteint, nous pouvons voir un **net avantage en faveur d'une solution sans VueX**, sauf p
C'est quoi la règle pour mettre les "..." ou le "etc." ?

2020-11-03 10:01 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ensuite, nous avons cherché a comparer avec le plus d'objectivité possible les 2 solutions. Si l'objectif est atteint, nous pouvons voir un **net avantage en faveur d'une solution sans VueX**, sauf p
@JulioJu, c'est pout toi.

2020-11-03 10:05 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ensuite, nous avons cherché a comparer avec le plus d'objectivité possible les 2 solutions. Si l'objectif est atteint, nous pouvons voir un **net avantage en faveur d'une solution sans VueX**, sauf p
@JulioJu, formateur sogilis en rédaction !

2020-11-03 10:07 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Toujours est-il que cela a un coût, et notamment au niveau de la navigabilité dans le code. En effet, les éditeurs et autres IDE ne permettent généralement pas naviguer de `this.commit('increment')`
", et" : on peut omettre la virgule quand il y a un "et" non ?

2020-11-03 10:09 UTC, Scra3 commented on site/layouts/shortcodes/pen.html
> +<p class="codepen"
On peut supprimer le fichier, on utilise plus codepen.

2020-11-03 10:31 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ensuite, nous avons cherché a comparer avec le plus d'objectivité possible les 2 solutions. Si l'objectif est atteint, nous pouvons voir un **net avantage en faveur d'une solution sans VueX**, sauf p
Si j'ai bien compris, ici on doit mettre "etc." à la place des "...". (voir slack pour les explications).

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +title: Vous utilisez VueX ? Alors vous avez raté quelque chose
```suggestion
title: Vous utilisez VueX ? Alors vous avez peut-être raté quelque chose
```

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +- **Exposer des fonctions "utilitaires"** (sans notion fonctionnelle) permettant l'accès et la modification de ces états. Cette partie n'est pas à négliger puisque le fonctionnement de Vue impose un
Des fonctions « sans notion fonctionnelle » c'est un peu bizare non ?

Peut-être « sans notion métier » ou rien ?

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +- **Exposer des fonctions "utilitaires"** (sans notion fonctionnelle) permettant l'accès et la modification de ces états. Cette partie n'est pas à négliger puisque le fonctionnement de Vue impose un
```suggestion
- **Exposer des fonctions "utilitaires"** (sans notion fonctionnelle) permettant l'accès et la modification de ces états. Cette partie n'est pas à négliger puisque le fonctionnement de Vue impose un certain  [boilerplate](https://en.wikipedia.org/wiki/Boilerplate_code) lors de la mutation de l'état (cf [documentation](https://fr.vuejs.org/v2/guide/reactivity.html#Limitations-de-la-detection-de-changement)). Note: ces objets représentant généralement des collections d'éléments, on voit alors apparaître quelque chose qui ressemble beaucoup au pattern [Repository](https://martinfowler.com/eaaCatalog/repository.html).
```

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +## Les avantages
Du coup plutôt

`Pourquoi ne pas se passer de VueX ?` non ?

Je suis d'accord avec @JulioJu sur le fair que le titre pourrait être meilleur.

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +title: Vous utilisez VueX ? Alors vous avez raté quelque chose
@JulioJu Proposait aussi `Pourquoi se passer de VueX ?`

Je pense qu'il manque une négation (« Pourquoi **ne pas** se passer de Vuex ? »), mais j'aime bien l'idée.

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Idem lorsque l'on veut ajouter une nouvelle fonctionnalité : on doit ouvrir le fichier dans lequel l'état est stocké pour ajouter un attribut, puis ouvrir le fichier des actions, etc. C'est lourd, et
```suggestion
Idem lorsque l'on veut ajouter une nouvelle fonctionnalité : on doit ouvrir le fichier dans lequel l'état est stocké pour ajouter un attribut, puis ouvrir le fichier des actions, etc. C'est lourd, et c'est d'autant plus **sujet à erreur** que ces éléments sont directement dépendants et éloignés les uns des autres.
```

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Mais ceci n'est qu'indirectement lié a VueX. En effet, comme conseillé dans [un coin de la documentation](https://vuex.vuejs.org/guide/structure.html), lorsque l'application commence à grossir, il pe
```suggestion
Mais ceci n'est qu'indirectement lié a VueX. En effet, comme conseillé dans [un coin de la documentation](https://vuex.vuejs.org/guide/structure.html), lorsque l'application commence à grossir, il peut être préférable de regrouper les états, actions, mutateurs et getters par domaine, en utilisant des modules, ce qui donne quelque chose comme ceci :
```

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +En somme, VueX risque d'enfermer dans une organisation technique du code qui n'aide pas à la maintenance.
```suggestion
En somme, l'utilisation de VueX risque d'enfermer les développements dans une organisation technique du code qui n'aide pas à la maintenance.
```

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +On imagine bien que ce problème ne se présente pas sans VueX, toujours pour la même raison : simple appel de fonction JS (ex: `Counter.increment()`).
```suggestion
On imagine bien que ce problème ne se présente pas sans VueX, toujours pour la même raison : on utilise un simple appel de fonction JS (ex: `Counter.increment()`).
```

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Il y a des applications où cela peut être utile, et beaucoup où ça ne l'est pas du tout. Nous avons constaté parmi les équipes que nous avons rencontrées que la plupart n'utilisent pas cet outil.
```suggestion
Il y a des applications où cela peut être utile, et beaucoup où ça ne l'est pas du tout. Nous avons constaté, parmi les équipes que nous avons rencontrées, que la plupart n'utilisent pas cet outil.
```

2020-11-03 10:36 UTC, vlamy commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ensuite, nous avons cherché a comparer avec le plus d'objectivité possible les 2 solutions. Si l'objectif est atteint, nous pouvons voir un **net avantage en faveur d'une solution sans VueX**, sauf p
Moi je prèfère la version de @JulioJu :smile: 

Désolé de mettre mon grain de sel

2020-11-03 10:44 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +En somme, VueX risque d'enfermer dans une organisation technique du code qui n'aide pas à la maintenance.
```suggestion
En somme, l'utilisation de VueX risque de contraindre les développements à organisation technique du code qui n'aide pas à la maintenance.```

2020-11-03 11:06 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +- **Exposer des fonctions "utilitaires"** (sans notion fonctionnelles) permettant l'accès et la modification de ces états. Cette partie n'est pas à négliger puisque le fonctionnement de Vue impose un
Ajout d'un lien hypertexte vers https://en.wikipedia.org/wiki/Boilerplate_code

2020-11-03 11:06 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +- **Exposer des fonctions "utilitaires"** (sans notion fonctionnelles) permettant l'accès et la modification de ces états. Cette partie n'est pas à négliger puisque le fonctionnement de Vue impose un
Qu'en penses-tu @aurelcarlier ?

2020-11-03 11:09 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +- **Exposer des fonctions "utilitaires"** (sans notion fonctionnelle) permettant l'accès et la modification de ces états. Cette partie n'est pas à négliger puisque le fonctionnement de Vue impose un
Done

2020-11-03 11:09 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +- **Exposer des fonctions "utilitaires"** (sans notion fonctionnelle) permettant l'accès et la modification de ces états. Cette partie n'est pas à négliger puisque le fonctionnement de Vue impose un
Done

2020-11-03 11:19 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +title: Vous utilisez VueX ? Alors vous avez raté quelque chose
Nous vous proposons ceci :
> Un état centralisé, oui, mais sans vuex !

2020-11-03 12:53 UTC, Scra3 commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ensuite, nous avons cherché a comparer avec le plus d'objectivité possible les 2 solutions. Si l'objectif est atteint, nous pouvons voir un **net avantage en faveur d'une solution sans VueX**, sauf p
```suggestion
En somme : plus grande simplicité du code, plus grande personnalisation de l'architecture, absence de dépendance à une librairie externe, pattern de programmation plus simple, navigabilité dans le code amélioré, moins de boilerplate pour les tests, tels sont les avantages de se passer de la bibliothèque VueX.
```

2020-11-04 13:11 UTC, ericwes reviewed
Quelques changements mineurs - deux réf au code source, une typo et une suggestion de référence au pattern Singleton - je vous laisse mesurer le degré de pertinence.

2020-11-04 13:11 UTC, ericwes commented on site/content/posts/2020-08-31-vuex-alternative.md
> +C'est toujours ça de pris, d'autant plus qu'il ne faut quasiment **aucune ligne de code supplémentaire pour remplacer VueX** !
```suggestion
C'est toujours ça de pris, d'autant plus qu'il ne faut quasiment **aucune ligne de code supplémentaire pour remplacer VueX** ! Du javascript natif et les mécanismes de réactivité de VueJS suffisent à implémenter ce besoin de [singleton](https://fr.wikipedia.org/wiki/Singleton_(patron_de_conception)) dans nos applications.
```

2020-11-04 13:46 UTC, florencedelbarre commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Bien souvent, les applications utilisant VueX sont organisées avec un découpage technique (les états regroupé, les actions regroupées, les mutateurs et les accesseurs) :
```suggestion
Bien souvent, les applications utilisant VueX sont organisées avec un découpage technique (les états regroupés, les actions regroupées, les mutateurs et les accesseurs) :
```

2020-11-04 13:54 UTC, florencedelbarre commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Ceci est ni plus ni moins qu'une architecture [CQRS](https://www.martinfowler.com/bliki/CQRS.html).
```suggestion
Ceci n'est ni plus ni moins qu'une architecture [CQRS](https://www.martinfowler.com/bliki/CQRS.html).
```

2020-11-04 13:56 UTC, florencedelbarre commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Au-delà de la complexité apportée par CQRS, ce pattern a quelques avantages, mais dont la plupart n'ont pas de sens côté front (ex: facilite l'event sourcing, la scalabilité horizontale…).
juste `mais la plupart `? Je trouve "mais dont la plupart" un peu lourd

2020-11-04 14:44 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +- **Exposer des fonctions "utilitaires"** (sans notion métier) permettant l'accès et la modification de ces états. Cette partie n'est pas à négliger puisque le fonctionnement de Vue impose un certain
```suggestion
- **Exposer des fonctions "utilitaires"** (sans notion métier) permettant l'accès et la modification de ces états. Cette partie n'est pas à négliger puisque le fonctionnement de Vue impose un certain [boilerplate](https://en.wikipedia.org/wiki/Boilerplate_code) lors de la mutation de l'état (cf [documentation](https://fr.vuejs.org/v2/guide/reactivity.html#Limitations-de-la-detection-de-changement)). Note : ces objets représentant généralement des collections d'éléments, on voit alors apparaître quelque chose qui ressemble beaucoup au pattern [Repository](https://martinfowler.com/eaaCatalog/repository.html).
```

2020-11-04 14:54 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +Au-delà de la complexité apportée par CQRS, ce pattern a quelques avantages, mais dont la plupart n'ont pas de sens côté front (ex: facilite l'event sourcing, la scalabilité horizontale…).
```suggestion
Au-delà de la complexité apportée par CQRS, ce pattern a quelques avantages, mais la plupart n'ont pas de sens côté front (ex: facilite l'event sourcing, la scalabilité horizontale…).
```

2020-11-04 15:01 UTC, jibidus commented on site/content/posts/2020-08-31-vuex-alternative.md
> +C'est toujours ça de pris, d'autant plus qu'il ne faut quasiment **aucune ligne de code supplémentaire pour remplacer VueX** !
Je pense que l'enjeu est plutôt sur le pattern observateur / réactif. Mais ça peut être interessant de rajouter ce point, en effet.

2020-11-05 22:20 UTC, Scra3 commented
On merge :) ?

2020-11-06 08:53 UTC, jibidus approved these changes

2020-11-06 08:56 UTC, merged