new article: les 10 commandements du test (WIP)
sogilis/Blog pull request #171
Opened 2020-09-15 12:48 UTC by jibidus

2020-11-13 08:38 UTC, vlamy commented on site/content/posts/2020-10-01-10-commandements-tests.md
> +- [ ] Trouver une image pour la page d'index
Propositions:

- https://search.creativecommons.org/photos/8618d05e-d608-462d-9a19-fbac4e887d25
- https://search.creativecommons.org/photos/7582fcd5-12b6-40c4-bbfb-6c26108ba4bb
- https://search.creativecommons.org/photos/33b025f9-9be2-40d9-8991-8a9f701962db
- https://search.creativecommons.org/photos/24ee9bcf-b48b-49d6-8837-c8e2fc98c068

2020-11-20 17:35 UTC, jibidus commented on site/content/posts/2020-10-01-10-commandements-tests.md
> +- [ ] Trouver une image pour la page d'index
best one est pas mal

2020-11-30 08:17 UTC, vlamy commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +date: 2020-10-01
:warning: changer la date si on ne veut pas que l'article apparaisse en 4ème position (après l'article sur VueX et les articles sur les drônes)

2020-11-30 09:11 UTC, vlamy requested changes

2020-11-30 09:11 UTC, vlamy commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- déplacer le code dans un "setup", "before each"…
```suggestion
- déplacer le code du boilerplate dans des méthodes de facilitations de type "setup", "before each", "after"…
```

2020-11-30 09:11 UTC, vlamy commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Concrètement, voilà ce que cela peut donner, en partant de ce test où la majorité du boilerplate est surligné :
```suggestion
Voici un exemple de test, dans lequel le boilerplate (beaucoup trop gros) est surligné :
```

2020-11-30 09:11 UTC, vlamy commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +En appliquant le principe a l'extrème, on peut arriver à ceci :
```suggestion
En réduisant le boilerplate a l'extrème, on peut arriver à ceci :
```

2020-11-30 09:11 UTC, vlamy commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +De plus, ce boilerplate est souvent commun a plusieurs tests. Cette étape permet ainsi de le factoriser, facilitant sa maintenance en minimisant la duplication.
```suggestion
De plus, notons que le boilerplate est souvent commun a plusieurs tests. Son extraction permet alors de le factoriser, facilitant sa maintenance, en minimisant la duplication. Attention toutefois à ne pas tomber dans l'excés en cherchant à factoriser trop de choses. L'élément important est d'extraire le boilerplate, sa factorisation n'est qu'une option, à étudier de façon opportuniste.
```

2020-11-30 09:11 UTC, vlamy commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Note : plus le test est haut niveau, plus ce boilerplate a tendance a être important.
```suggestion
**Note :** nous avons pu observé que plus le test est haut niveau, plus ce boilerplate a tendance a être important.
```

2020-11-30 09:11 UTC, vlamy commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Note : plus le test est haut niveau, plus ce boilerplate a tendance a être important.
Il faudrait dire ce que c'est « haut niveau » je pense non ? J'ai du mal  à trouver moi déjà.

2020-12-01 13:44 UTC, vlamy commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Imaginez que je sois développeur sur une partie non critique de mon application, qu'il y ait beaucoup de couplage sur cette base de code et que, cherchant à produire un code de qualité, j'écrive des
```suggestion
Imaginez que je sois développeur sur une partie non critique de mon application, qu'il y ait beaucoup de couplage sur cette base de code et que, cherchant à produire un code de qualité, j'écrive des **tests unitaires pour chaque cas de chaque fonction**, y compris pour les fonctions les plus triviales. Résultat : chaque modification du code testé, fusse-t-elle un refacto de quelques lignes, risque d'engendrer des adaptations dans beaucoup de tests, ce qui implique un **coût non négligeable**. Il est alors important de se demander si le temps passé à l'écriture de certains de ces tests aurait peut-être été plus utile sur une autre tâche (comme l'écriture de tests de plus haut niveau).
```

2020-12-01 14:19 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Dans cet article, il est question de tests logiciel, mais pas n'importe quel test quel que soit le **contexte** :
```suggestion
Dans cet article, il est question de certains type de tests logiciels, ou plus précisément :
```

2020-12-01 15:38 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +date: 2020-10-01
On ferra ça juste avant de merger, oui.

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- base de code maintenable et évolutive (pas de code jetable, de [POC](https://fr.wikipedia.org/wiki/Preuve_de_concept)…)
```suggestion
Dans cet article, nous parlerons de certains types de tests logiciels. Plus précisément, il sera question de tests automatisés (pas de tests manuels) portant sur une base de code maintenable et évolutive (pas de code jetable, de [POC](https://fr.wikipedia.org/wiki/Preuve_de_concept), etc.).
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +L'idée derrière ce principe est de faciliter au maximum la compréhension du code du test[^testcode], par exemple pour la maintenance future par un développeur tiers. En effet, lorsqu'on est amené à f
```suggestion
L'idée derrière ce principe est de faciliter au maximum la compréhension du code du test[^testcode], par exemple pour la maintenance future par un développeur tiers. En effet, lorsqu'on est amené à faire évoluer un test existant, il est important de **comprendre le cas de test rapidement**. Et si ce code est **noyé au milieu de détails techniques**, cette tâche devient fastidieuse.
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Et pour comprendre ce cas de test rapidement, il n'y a pas 36 solutions : il doit être décrit entièrement dans le code du test[^testcode]. Pas d'indirection, pas de logique caché dans un autre fichie
```suggestion
Et pour comprendre ce cas de test rapidement, il n'y a pas 36 solutions : il doit être décrit entièrement dans le code du test[^testcode]. Pas d'indirection, pas de logique caché dans un autre fichier, etc. Après avoir lu ce code de test, le développeur doit être capable de répondre aux questions suivantes :
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Bien sûr, ces différents facteurs **dépendent du contexte**. Par exemple, sur une application critique, ce surcoût sera peut-être largement amorti par la réduction du risque de défaillance et leurs c
```suggestion
Bien sûr, ces différents facteurs **dépendent du contexte**. Par exemple, sur une application critique, ce surcoût sera peut-être largement amorti par la réduction du risque de défaillance et leurs conséquences en perte financière ou humaine…
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +C'est pourquoi, autant que faire se peut, il est préférable de limiter au maximum le jeu de test utilisé. Les jeux de données communs a plusieurs tests (généralement utilisé avec les fixtures de test
```suggestion
C'est pourquoi, autant que faire se peut, il est préférable de limiter au maximum le jeu de test utilisé. Les jeux de données communs a plusieurs tests (généralement utilisés avec les fixtures de test[^testfixture]) sont à éviter, mais nous en reparlerons plus tard.
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Heureusement, des stratégies (architectures, frameworks, etc.) existent pour limiter ce surcoût, mais toutes ne sont pas disponibles quelque soit le contexte.
```suggestion
Heureusement, des stratégies (architectures, frameworks, etc.) existent pour limiter ce surcoût, mais toutes ne sont pas disponibles dans tous les contextes.
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Voici quelques axes de coûts pour aider à la réflexion :
Axes de coûts ? Est-il possible de reformuler ?
-> Voici quelques exemples concrets rencontrés en pratiques ?

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Comprendre quelle était l'intention demande un soupçon d'investigation, alors qu'il existe souvent des solutions peut coûteuses pour améliorer la situation.
```suggestion
Comprendre quelle était l'intention demande un soupçon d'investigation, alors qu'il existe souvent des solutions peu coûteuses pour améliorer la situation.
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +En voici un premier exemple naïf où l'on a créé préalablement une méthode `assertMessageMatches()` :
```suggestion
Voici un premier exemple naïf où l'on a créé préalablement une méthode `assertMessageMatches()` :
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +**Note :** l'utilisation d'assertions personnalisées (cf exemple naïf) est une option a ne pas négliger
```suggestion
**Note :** l'utilisation d'assertions personnalisées (cf. exemple naïf) est une option a ne pas négliger.
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- **Utiliser une fixture existante ?** Le jeu de données sera nécessairement plus important que nécessaire, puisque partagé entre plusieurs tests qui requièrent chacun des données différentes. En cas
double emploi de nécessaire ici à éviter

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- **Adapter une fixture existante ?** On prend alors le risque de casser un autre test qui utilise cette fixture car on ne sait pas quel élément de la fixture est importante pour quel test.
```suggestion
- **Adapter une fixture existante ?** On prend alors le risque de casser un autre test qui utilise cette fixture car on ne sait pas quel élément de la fixture est important pour quel test.
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- **Créer une nouvelle fixture ?** Multipliant les fixtures alourdi la modification du modèle de données.
```suggestion
- **Créer une nouvelle fixture ?** Multiplier les fixtures alourdi la modification du modèle de données.
```

2020-12-01 16:50 UTC, aurelcarlier commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Pour toutes ces raisons, il est préférable de privilégier la création de données à la volée à travers un DSL clair et paramétrable (ex: [Object Mother et Builder en Java](/posts/2019-01-11-object-mot
DSL ?

2020-12-01 16:58 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Pour toutes ces raisons, il est préférable de privilégier la création de données à la volée à travers un DSL clair et paramétrable (ex: [Object Mother et Builder en Java](/posts/2019-01-11-object-mot
En effet. J'ai remplacé par ça : "il est préférable de privilégier la création de données à la volée à travers des functions claires et paramétrables"

2020-12-01 16:59 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- **Utiliser une fixture existante ?** Le jeu de données sera nécessairement plus important que nécessaire, puisque partagé entre plusieurs tests qui requièrent chacun des données différentes. En cas
1er nécessaire remplacé par "alors".

2020-12-02 07:00 UTC, s-de-beer commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- que veut-on tester ? `TournamentAPI.joust()` ou `fight()` ?
Je trouve cet exemple un peu flou. D'ou sort le TournamentAPI.joust()? Pourquoi mockWinner est pas bon et buildHero ok? Pourquoi tu ne dis rien du loser = buildHero? On pourrait penser buildLoser()?

2020-12-02 07:59 UTC, bdumas1 commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Un nouveau développeur doit pouvoir comprendre rapidement le cas testé. Pourquoi ? Parce qu'un développeur passe beaucoup de temps a lire du code (notamment des tests), et le cas de test est finaleme
```suggestion
Un nouveau développeur doit pouvoir comprendre rapidement le cas testé. Pourquoi ? Parce qu'un développeur passe beaucoup de temps à lire du code (notamment des tests), et le cas de test est finalement la première étape permettant de comprendre le code du test. C'est un peu comme n'importe quel sujet : on commence par assimiler les concepts globaux, puis on rentre de plus en plus dans les détails. Faire le chemin dans l'autre sens est plus difficile.
```

2020-12-02 08:00 UTC, Scra3 commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Dans cet article, nous allons parler de **stratégies moins connues**, mais qui permettent de gagner encore un peu plus en lisibilité, maintenabilité, évolutivité et **utilisabilité au quotidien**.
On dit déjà "dans cet article" un peu plus haut. On pourrait trouver une autre formulation.

2020-12-02 08:14 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- que veut-on tester ? `TournamentAPI.joust()` ou `fight()` ?
Tu as raison, l'exemple n'est pas génial.

Peut-être qu'il faut quelque chose de plus simple comme ceci ?

Autre exemple :

```javascript {linenos=inline}
 describe('Excalibur', () => {
     it('changeBearer() returns sparkling excalibur when bearer has destiny', async () => {
         const hero = buildHero();
         excalibur = buildExcalibur().changeBearer(hero)
         expect(excalibur.isSparkling).toBeTruthy();
     });
 });
 ```

En lisant le code, on comprend que n'importe quel hero peut faire étinceler excalibur, alors que seuls ceux qui ont une destiné devraient pouvoir. Pourtant le test fonctionne puisque `buildHero()` retourne un héro ayant une destiné :

 ```javascript
function buildHero() {
   return {
      id: 3,
      name: 'Perceval,
      hasDestiny: true,
      rank: 'Knight',
   };
}
 ```

Soit cette fonction `buildHero()` est mal nommée (et devrait s'appeler `buildHeroWithDetiny()`), soit il manque quelque chose dans le test (comme `hero.hasDestiny = true`).

2020-12-02 08:16 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Dans cet article, nous allons parler de **stratégies moins connues**, mais qui permettent de gagner encore un peu plus en lisibilité, maintenabilité, évolutivité et **utilisabilité au quotidien**.
Que penses-tu de cela ?
```suggestion
Ici, nous aborderons des **stratégies moins connues**, mais qui permettent de gagner encore un peu plus en lisibilité, maintenabilité, évolutivité et **utilisabilité au quotidien**.
```

2020-12-02 08:19 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Voici quelques axes de coûts pour aider à la réflexion :
Que penses-tu de ceci ?
```suggestion
Voici quelques exemples concrets rencontrés :
```

2020-12-02 08:56 UTC, vlamy commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- que veut-on tester ? `TournamentAPI.joust()` ou `fight()` ?
la dernière version est mieux :+1:

2020-12-02 15:55 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +[^boilerplate]: le **boilerplate** est du code purement technique nécessaire au fonctionnement du test, mais ne portant aucune information sur le cas testé. Exemples : `TRUNCATE` de tables avant ou a
From @Isabelledonne :
Techniquement, la définition du boilerplate peut-être contestée (dans l'acceptation usuelle du terme, c'est plutôt du code répétitif que du code technique), mais on est d'accord que dans la pratique, dans les tests, les deux notions vont la plupart du temps recouvrir les même portions de code.

> boilerplate : se dit pour une fonctionnalité d'un programme informatique dont le code source est quasiment le même quel que soit le programme (boilerplate code)

2020-12-02 15:55 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +[^testcode]: le **code du test** est le code présent dans la fonction décrivant le test. On ne parle ici que du code appelé indirectement.
From @Isabelledonne :
pas sûre de comprendre exactement ce qu'on veut dire par "appelé indirectement" ?

2020-12-02 15:55 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- plus un test est bas niveau[^testlevel], plus il y a de risque d'engendrer un surcoût lors d'un refactoring.
From @Isabelledonne :
??? mériterait une petite explication ou un exemple ? pourquoi est-ce que c'est le cas ?

2020-12-02 15:58 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +[^boilerplate]: le **boilerplate** est du code purement technique nécessaire au fonctionnement du test, mais ne portant aucune information sur le cas testé. Exemples : `TRUNCATE` de tables avant ou a
Tout a fait, peut-être peut-on ajouter ceci pour être moins sujet a débat?

```suggestion
[^boilerplate]: le mot **boilerplate** est utilisé ici pour décrire du code purement technique nécessaire au fonctionnement du test, mais ne portant aucune information sur le cas testé. Exemples : `TRUNCATE` de tables avant ou après le test, création d'utilisateur par défaut, instanciation d'une classe dont on teste une méthode…
```

2020-12-02 16:02 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +[^testcode]: le **code du test** est le code présent dans la fonction décrivant le test. On ne parle ici que du code appelé indirectement.
Pour moi, lorsqu'une fonction A appelle une fonction B qui appelle une fonction C, alors A appelle C indirectement.

Peut-être quelque chose comme ça pour être plus clair ?
```suggestion
[^testcode]: le **code du test** est le code présent dans la fonction décrivant le test. On ne parle ici que du code appelé indirectement dans l'implémentation du test.
```

2020-12-02 16:07 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- plus un test est bas niveau[^testlevel], plus il y a de risque d'engendrer un surcoût lors d'un refactoring.
Ca mériterait pas mal d'explications pour décrire ça je pense, idéalement avec des schémas, voir du code. Du coup, je ne sais pas trop comment traiter ça.

- supprimer cette ligne (c'est dommage, c'est un élément intéressant dans la réflexion je trouve)
- ajouter une note de base de page (je ne suis pas sûr de parvenir à expliquer ça clairement en un seul paragraphe)
- autre ?

Ca pourrait être le sujet d'un autre article de blog par contre… et ferrait alors pointer cette ligne sur le nouvel article.

2020-12-02 16:14 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- que veut-on tester ? `TournamentAPI.joust()` ou `fight()` ?
Exemple modifié

2020-12-03 07:55 UTC, Isabelledonne commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +[^boilerplate]: le **boilerplate** est du code purement technique nécessaire au fonctionnement du test, mais ne portant aucune information sur le cas testé. Exemples : `TRUNCATE` de tables avant ou a
Oui parfait, du coup on pose les conventions pour l'acceptation du terme "boilerplate" dans notre cas.
Ca me paraît une bonne solution.

2020-12-03 08:00 UTC, Isabelledonne commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +[^testcode]: le **code du test** est le code présent dans la fonction décrivant le test. On ne parle ici que du code appelé indirectement.
Avec l'exemple je comprends bien ce que tu entends par "appelé indirectement".
S'il n'y a que moi qui me suis posé la question, et que tous les autres ont tout de suite compris que ça correspondait à ceci : "lorsqu'une fonction A appelle une fonction B qui appelle une fonction C, alors A appelle C indirectement.", alors l'exemple est superflu.
Sinon, peut-être que l'exemple serait utile...

2020-12-03 08:01 UTC, Isabelledonne commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- plus un test est bas niveau[^testlevel], plus il y a de risque d'engendrer un surcoût lors d'un refactoring.
La dernière solution (faire référence à un article à venir) me paraît parfaite.

2020-12-03 08:53 UTC, vlamy approved these changes

2020-12-07 15:55 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- plus un test est bas niveau[^testlevel], plus il y a de risque d'engendrer un surcoût lors d'un refactoring.
Done

2020-12-07 15:56 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +[^testcode]: le **code du test** est le code présent dans la fonction décrivant le test. On ne parle ici que du code appelé indirectement.
J'ai du mal à trouver une formulation qui explique ça clairement (le mieux serait un exemple, mais pas trop la place dans ces footnotes). Et n'ayant qu'un seul retour sur ce point, je lâche l'affaire, mais à charge de revanche 😉.

2020-12-07 16:21 UTC, merged

2020-12-09 07:44 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Dans cet article, nous parlerons de certains types de tests logiciels. Plus précisément, il sera question de tests automatisés (pas de tests manuels) portant sur une base de code maintenable et évolu
Oui, ce n'est pas forcément super fluide.
Par contre, je pense qu'il ne faut pas laisser entendre que le scope correspond à tout test automatisé, sinon on met un pas sur le terrain du dogmatisme.

2020-12-09 08:00 UTC, Liveche commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Dans cet article, nous parlerons de certains types de tests logiciels. Plus précisément, il sera question de tests automatisés (pas de tests manuels) portant sur une base de code maintenable et évolu
oui je suis d'accord, je ne voulais pas dire de supprimer le reste :)  "nous parlerons de tests automatisés (pas de tests manuels)  portant sur une base de code maintenable et évolutive (pas de code jetable, de [POC](https://fr.wikipedia.org/wiki/Preuve_de_concept), etc.)."

2020-12-09 08:01 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Dans cet article, nous parlerons de certains types de tests logiciels. Plus précisément, il sera question de tests automatisés (pas de tests manuels) portant sur une base de code maintenable et évolu
Ah oui, je vois ! 👍

2020-12-09 08:07 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- toute la partie connexion de la base de donnée a été déplacée en amont, pour être exécutée avant chaque test.
Pourquoi retirer le tier ? Du moins pourquoi ici et pas sur les lignes suivantes ?

2020-12-09 08:11 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- il est plus coûteux de trouver la cause d'un test en échec s'il est de haut niveau que s'il est de bas niveau.
Non, pour moi, ce n'est pas directement lié.

2020-12-09 08:20 UTC, jibidus commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +Certes les commentaires présentent de nombreux inconvénients, mais dans certaines situations bien particulières, les bénéfices peuvent l'emporter.
Je pense qu'on peut l'accepter. En effet, si on veut éviter ce type de question, j'ai bien peur qu'un article de blog ne soit pas suffisant, tellement on aborde de concepts et tellement il y a de limite dans telle ou telle situation.

2020-12-09 08:42 UTC, Liveche commented on site/content/posts/2020-10-01-principes-caches-du-test.md
> +- toute la partie connexion de la base de donnée a été déplacée en amont, pour être exécutée avant chaque test.
retirer le tiret? Je pense que c'est une erreur. J'ai édité mon commit.