Doc: describe the content format in details
sogilis/Blog pull request #181
Opened 2020-10-02 13:15 UTC by jibidus

2020-10-03 13:44 UTC, JulioJu requested changes

2020-10-03 13:44 UTC, JulioJu commented on docs/content-format.md
> +- [GitHub flavored syntax](https://guides.github.com/features/mastering-markdown/)
Nine, it's a Hugo Flavor, the Hugo Flavor . Sadly.

2020-10-03 13:44 UTC, JulioJu commented on docs/content-format.md
> +- make sure `NetlifyCMS` can handle this format
Just for info. It seems that @gitae03  have some troubleshooting with Asciidoctor and Reveal.JS. If I have understand well, the official format form Reveal.JS is Markdown, and the format Asciidoctor is quite abandoned. I don't understand if we have the same problem with Hugo, I don't know.

Maybe be careful to not advise a format that is less supported ! And if we switch to an other Static Site Generator, maybe Markdown could be quite sufficient for us (I've checked).

2020-10-03 13:44 UTC, JulioJu commented on README.md
> +   Only `Markdown` is supported with following [syntax](https://commonmark.org/help/) (more details [here](docs/content-format.md)).
Nine, it's a Hugo Flavor, the Hugo Flavor . Sadly.

2020-10-03 17:00 UTC, jibidus commented on docs/content-format.md
> +- [GitHub flavored syntax](https://guides.github.com/features/mastering-markdown/)
Où as tu vu cette info ?

Moi, j'ai vu ça sur [une release node de Hugo](https://gohugo.io/news/0.60.0-relnotes/):
> It’s CommonMark compliant and GitHub flavored

Bon, c'est un article rédigé par l'équipe de Hugo, donc pas forcément obectif.
Je ferrai un petit test pour vérifier ça, au moins on sera fixé.

2020-10-03 17:03 UTC, jibidus commented on docs/content-format.md
> +- make sure `NetlifyCMS` can handle this format
I don't understand why we need a JS library to handle asciidoc, since asciidoctor is able to generate html (and html is sufficient for blog content).

2020-10-03 17:15 UTC, jibidus commented on docs/content-format.md
> +- [GitHub flavored syntax](https://guides.github.com/features/mastering-markdown/)
Bon, j'ai pas pu attendre : #84 
Résultat : c'est batard, certaines flavor Github sont supportées, par d'autres.

Je vais mettre a jour la doc

2020-10-07 15:05 UTC, JulioJu commented on docs/content-format.md
> +- [GitHub flavored syntax](https://guides.github.com/features/mastering-markdown/)
Je ne comprends pas. #84 renvoie sur un lien qui ne semble pas correspondre au problème actuel.

Pour info https://gohugo.io/content-management/shortcodes/

2020-10-07 15:08 UTC, jibidus commented on docs/content-format.md
> +- [GitHub flavored syntax](https://guides.github.com/features/mastering-markdown/)
En effet, c'était #184 qu'il fallait écrire.

2020-10-07 15:09 UTC, JulioJu commented on docs/content-format.md
> +- make sure `NetlifyCMS` can handle this format
Sorry I was not clear.

It's not important.

2020-10-07 15:40 UTC, JulioJu commented on docs/content-format.md
> +- [GitHub flavored syntax](https://guides.github.com/features/mastering-markdown/)
Ok autant pour moi.

Dans la doc il serait peut-être intéressant de mettre un lien vers https://gohugo.io/content-management/shortcodes/ en précisant que c'est déconseillé de les utiliser car ça diminue la portabilité du contenu.

Autant utiliser du Markdown simple.

2020-10-08 08:22 UTC, JulioJu commented on docs/content-format.md
> +In addition, Hugo provide many [built in shortcodes](https://gohugo.io/content-management/shortcodes/#use-hugos-built-in-shortcodes), but let's try as much as possible to use "standard" Markdown, sin
Cool paragraph :-)

2020-10-08 08:22 UTC, JulioJu commented on README.md
> +   Only `Markdown` is supported with following [syntax](https://commonmark.org/help/) (more details [here](docs/content-format.md)).
J'ai dit une boulette ici comme me l'a indiqué @jibidus  voir https://github.com/sogilis/Blog/pull/184

2020-10-08 08:22 UTC, JulioJu commented on docs/content-format.md
> +Only supporter format is `Markdown`, more precisely [CommonMark](https://commonmark.org) compliant and [GitHub flavored](https://github.github.com/gfm/):
Peut-être ajouter un lien vers https://gohugo.io/content-management/formats/#learn-markdown ? 

Ce qui permettrait peut-être de clore le ticket https://github.com/sogilis/Blog/issues/185 ?

2020-10-08 08:22 UTC, JulioJu commented on README.md
> +   Only `Markdown` is supported with following [syntax](https://commonmark.org/help/) (more details [here](docs/content-format.md)).
Plutôt ajouter le lien vers la doc officielle d'Hugo https://gohugo.io/content-management/formats/#learn-markdown ce qui permet de clore  https://github.com/sogilis/Blog/issues/185  ?

2020-10-08 08:27 UTC, jibidus commented on docs/content-format.md
> +Only supporter format is `Markdown`, more precisely [CommonMark](https://commonmark.org) compliant and [GitHub flavored](https://github.github.com/gfm/):
Pourquoi ajouter ce lien ?

PS : le lien sur `CommonMark` point sur une gros bouton `Learn markdown in 60 seconds` qui me semble un bon point de départ.

2020-10-08 08:28 UTC, JulioJu commented on docs/content-format.md
> +Only supporter format is `Markdown`, more precisely [CommonMark](https://commonmark.org) compliant and [GitHub flavored](https://github.github.com/gfm/):
Ok cool :-)

2020-10-08 08:30 UTC, jibidus commented on README.md
> +   Only `Markdown` is supported with following [syntax](https://commonmark.org/help/) (more details [here](docs/content-format.md)).
Le fichier `docs/content-format.md` donne des informations qui ne sont pas dans la doc de Hugo. Et ces informations me semblent utiles (voir indispensables) pour pour les auteurs (ex: comment écrire des notes de pied de page ? Comment ajouter de emoji ?).

2020-10-08 08:32 UTC, JulioJu commented on README.md
> +   Only `Markdown` is supported with following [syntax](https://commonmark.org/help/) (more details [here](docs/content-format.md)).
Ok d'ac.

Oui inutile de surcharger, ok ;-) . Pardon j'avais mal vu ;-)

2020-10-08 08:33 UTC, JulioJu approved these changes

2020-10-08 08:48 UTC, JulioJu commented on docs/content-format.md
> +- make sure `NetlifyCMS` can handle this format
@jibidus  Ce que je voulais dire maladroitement c'est que peut-être qu'Asciidoc pouvait poser des problèmes car il est peut-être moins bien supporté.

Voir par exemple ce qu'Okta a rencontré comme problème https://github.com/oktadeveloper/okta-blog-hugo/issues/6 

Ce que je disais dans un précédant commentaire, c'est que sur le papier Asciidoc c'est mieux que Makrdown, mais c'est peut-être moins bien supporté. Ça me semble être intéressant de mettre un warning en ce sens.

2020-10-08 13:26 UTC, jibidus commented on docs/content-format.md
> +- make sure `NetlifyCMS` can handle this format
Je peux rajouter une bafouille, ça ne coûte rien.

2020-10-08 13:34 UTC, merged

2020-10-08 14:44 UTC, JulioJu commented on docs/content-format.md
> +- make sure `NetlifyCMS` can handle this format
Cool :-)