[WIP] - feature: add search
sogilis/Blog pull request #199
Opened 2020-10-26 13:42 UTC by bdumas1

2020-10-27 18:10 UTC, JulioJu commented
@bdumas1 si on passe sous Nuxt.JS prochainement… Peut-être que ce ne serait pas la même chose du coup ?

2020-10-28 06:57 UTC, bdumas1 commented
Si on passe sur Nuxt prochainement, ça remet en question tout ce code car il sera implémenter autrement.
Autrement dit, ta question sous-entends que ça ne sert à rien de donner plus d'énergie aujourd'hui sur cette fracture, c'est bien ça ?
@jibidus qu'en penses-tu ?

2020-10-30 09:41 UTC, jibidus commented
J'ai du mal a estimé quand est-ce qu'on passerait le blog sur Nuxt (je pense que ça dépend du temps qu'on a pour avancer sur les sujets plus prioritaires que Next et là je n'ai aucune visibilité).
Mais a vue de next, je pense que le boulot déjà fait est quasiment mergable, ce qui permettra d'avoir les premiers retours de nos évangélistes par exemple, voir même avoir des stats d'utilisation (lorsqu'on aura Google Analytics ou autre) et pouvoir confirmer que cette feature est utile (ou pas).

2020-11-02 19:04 UTC, JulioJu commented
De tout façon vu qu'on a appris que le passage à Nuxt était remis aux calendes grecques, ma remarque n'a plus d'intérêt. Si on était de l'ordre e la semaine, ma remarque aurait pu avoir un intérêt. mais clairement ce n'est plus le cas.

2020-11-05 20:35 UTC, jibidus reviewed
Ca marche plutôt bien !
Peut-être un petit défaut : ça ne fonctionne pas sur mobile (l'input de recherche n'est pas visible dans le menu mobile). Mais je pense qu'on peut s'en passer pour l'instant, c'est déjà une belle étape.
J'ai ajouté quelques commentaires.
Des tests seraient pas mal aussi, il y a quand même pas mal de code js. Maintenant que le code est fait et fonctionne, on peut prévoir ça pour plus tard.

2020-11-05 20:35 UTC, jibidus commented on site/themes/sogilis/static/js/scripts.js
> +const getFilteredPosts = async () => {
s/get/fetch ?
`get` est généralement assimilé à un getter, du coup cela peut être confusant ici.

2020-11-05 20:35 UTC, jibidus commented on site/themes/sogilis/static/js/scripts.js
> +    return response.json().then((posts) => posts);
Il y a un truc qui m'échappe ici, ça fait quoi `.then((posts) => posts);` ?

2020-11-05 20:35 UTC, jibidus commented on site/themes/sogilis/static/js/scripts.js
> +    this.element.firstElementChild.innerHTML = this.element.firstElementChild.innerHTML.replace(
Je pense qu'il y a un truc qui cloche entre le nom de la fonction (`getMatchedElement `) et le fait qu'elle modifie `this.element`. Je dirais que c'est soit l'un soit l'autre, mais pas les deux, non ?

2020-11-05 20:35 UTC, jibidus commented on site/themes/sogilis/static/js/scripts.js
> +            regexp: new RegExp(`${term}`, 'giu'),
Beaucoup de niveaux d'indentation (5) ici pour que ce soit lisible je trouve.

2020-11-05 20:35 UTC, jibidus commented on .gitignore
> +/site/themes/sogilis/layouts/_default/list.json.json
C'est normal le `.json` en double ?

2020-11-06 07:16 UTC, bdumas1 commented on site/themes/sogilis/static/js/scripts.js
> +    return response.json().then((posts) => posts);
Oui, rien de plus que `response.json()`, c'est un peu du code mort que j'avais mis pour tester. Je corrige.

2020-11-06 07:22 UTC, bdumas1 commented on site/themes/sogilis/static/js/scripts.js
> +    this.element.firstElementChild.innerHTML = this.element.firstElementChild.innerHTML.replace(
Alors c'est peut être le nom `getMatchedElement` qui n'est pas le bon, même si je trouve qu'il va pas mal.
L'idée ici, c'est de retourner l'élément qui match avec la recherche et en surlignant ce qui correspond.

Est-ce que le mieux serait de séparer en 2 fonctions ? 
- `getMatchedElement(regexp)` retournerait juste l'élément qui match
- et à l'intérieur je ferais un `hightlightSearchString(regexp)` qui irait modifier `this.element` avec la `mark`

Qu'en penses-tu ?

2020-11-06 07:24 UTC, bdumas1 commented on site/themes/sogilis/static/js/scripts.js
> +            regexp: new RegExp(`${term}`, 'giu'),
C'est eslint/prettier qui est configuré comme ça quand je formate. Ça ne me gène pas plus pour la compréhension.
Je peux éventuellement découper en variable `posts` et `regexp`, qu'en penses-tu ?

2020-11-06 07:28 UTC, jibidus commented on site/themes/sogilis/static/js/scripts.js
> +    this.element.firstElementChild.innerHTML = this.element.firstElementChild.innerHTML.replace(
Si on veut juste retourner l'élément qui match, pourquoi modifier un état interne a la classe (`this.element`) ?
J'ai l'impression que `this.element` ne sert qu'a transmettre un truc entre le constructeur et cette fonction, je me trompe ?

2020-11-06 07:29 UTC, bdumas1 commented on site/themes/sogilis/layouts/_default/list.json.json
> +{{ $.Scratch.Add "index" slice }}
Si justement il doit être commité, je l'enlève du `.gitignore`.

2020-11-06 07:31 UTC, bdumas1 commented on .gitignore
> +/site/themes/sogilis/layouts/_default/list.json.json
J'ai supprimé cette ligne. C'est ce qui va renvoyer les posts quand on va appeler `/posts/index.json`.
Hugo fonctionne ainsi, de ce que j'ai lu sur [un tuto](https://forestry.io/blog/build-a-json-api-with-hugo/#output-formats) le double `.json` semble être normal oui.

2020-11-06 07:35 UTC, bdumas1 commented
> Peut-être un petit défaut : ça ne fonctionne pas sur mobile (l'input de recherche n'est pas visible dans le menu mobile). Mais je pense qu'on peut s'en passer pour l'instant, c'est déjà une belle étape.

Oui, je n'ai pas trop eu le temps de regarder la partie mobile, et je n'ai pas vu c-ça comme une prio à court terme.
Sur Basecamp on avait mis l'échéance fin novembre, je peux encore me trouver du temps pour regarder de fixer ça en mobile (il manque aussi une croix pour fermer les résultats de recherche).

> Des tests seraient pas mal aussi, il y a quand même pas mal de code js. Maintenant que le code est fait et fonctionne, on peut prévoir ça pour plus tard.

Yes, je me suis fais la même réflexion, mais je n'ai pas eu plus de temps pour le moment d'en mettre en place. Sur un site statique comme ici, tu me conseillerais une techno pour faire ça ?

2020-11-06 07:39 UTC, bdumas1 commented on .gitignore
> +/site/themes/sogilis/layouts/_default/list.json.json
En fait, je cherchais à le mettre plutôt dans le `.prettierrc`, et quand je le fais, il se met automatiquement dans le `.gitignore`. Je regarde pour trouver une solution.

2020-11-06 07:41 UTC, jibidus commented on site/themes/sogilis/static/js/scripts.js
> +            regexp: new RegExp(`${term}`, 'giu'),
Le problème racine derrière cette indentation, c'est le nombre de contextes imbriqués (il y a 5 fonctions imbriquées les unes dans les autres). Et pour chaque imbrication, le lecteur doit garder en tête le contexte parent pour comprendre a quoi sert la fonction enfant. Résultat : il faut garder beaucoup de choses en tête lorsqu'on arrive en bas de la pille.

Quelque chose comme ça est plus "léger" a lire par exemple :
```js
submitCallback = event => {
   event.preventDefault();
   const term = this.input.value.trim();
   if (!term) {
      return;
   }
   
   applyFilter = data => {
      xxx = {
         posts: data.map(…)
         regexp: new RegExp(`${term}`, 'giu'),
      };
      this.search(xxx);
   };
   getFilteredPosts().then(applyFilter)
};
this.form.addEventListener(('submit', submitCallback);
```

2020-11-06 07:42 UTC, bdumas1 commented on site/themes/sogilis/static/js/scripts.js
> +    this.element.firstElementChild.innerHTML = this.element.firstElementChild.innerHTML.replace(
Parce que je boucle sur une collection d'items et chaque item est une instance de cette classe. Si ça match, je retourne l'élément avec la mark associée.

2020-11-06 07:59 UTC, bdumas1 commented on site/themes/sogilis/static/js/scripts.js
> +            regexp: new RegExp(`${term}`, 'giu'),
Je ne suis pas très enthousiaste avec ton exemple, je trouve qu'on part un peu de partout.
Ce qu'on veut ici, c'est faire une recherche :
- sur les posts
- avec une regexp précise

Une autre possibilité pourrait être de faire le fetch des posts directement dans la fonction `search`, ainsi cette dernière ne prendrait en paramètre que la regexp. On ferait donc une recherche sur un regexp précise, et la fonction `search` aurait comme responsabilité de récupérer les posts et d'afficher ceux qui corresponde à la regexp.

2020-11-06 19:46 UTC, jibidus commented on site/themes/sogilis/layouts/_default/list.json.json
> +{{ $.Scratch.Get "index" | jsonify }}
Par curiosité, j'ai regardé comment ça marchait ces `.json.json` et j'ai pigé 2/3 trucs.
Je pense qu'on peut faire beaucoup plus simple avec juste ça (j'ai testé, ça fait le job) :
```
[
  {{ range $index, $e := (where .Site.AllPages.ByDate "Kind" "page").Reverse }}
    {{ if $index }}, {{ end }}
    {
      "id": {{ $index }},
      "title": {{ .Title | jsonify }},
      "url" : {{ .Permalink | jsonify }}
    }
  {{ end }}
```

PS : en enlevant l'attribut content (vu que pas encore utilisé), on gagne pas mal en temps de réponse.

2020-11-09 08:15 UTC, bdumas1 commented on site/themes/sogilis/layouts/_default/list.json.json
> +{{ $.Scratch.Get "index" | jsonify }}
J'avais repris ça d'un article sur le net par manque de temps, et je voulais le refacto. Merci, c'est mieux ainsi 👍

2020-11-10 20:58 UTC, jibidus approved these changes
Je pense qu'on peut ouvrir la MR a la revue avant de merger.
Moi en tout cas, ça me semble bien comme première étape.

2020-11-10 20:59 UTC, bdumas1 commented
> Je pense qu'on peut ouvrir la MR a la revue avant de merger.
> 
> Moi en tout cas, ça me semble bien comme première étape.

Je suis en train de faire la version mobile, c'est presque terminé, j'aimerais le pousser demain.

2020-11-20 07:59 UTC, jibidus commented
J'ai testé sur [app.lambdatest.com](app.lambdatest.com) (1h gratuit par mois), voila ce que j'ai trouvé :
- Lorsqu'on click sur la loupe, le focus n'est pas mis sur l'input, le clavier virtuel n'apparait donc pas tout de suite
- [complètement subjectif] Lorsqu'on valide la recherche l'input de recherche reste affiché. Ca fait bizarre je trouve, peut-être manque-t-il juste un peu de marge pour éloigner les résultats du champ de recherche, ce qui posera un problème si le champ de recherche est retiré (en clickant sur la loupe), puisqu'on aura alors une très grosse marge entre le "menu" et les résultats. Idée : mettre le champ de recherche sur la ligne de "menu", comme sur desktop finalement ?
- Lorsque j'ai clické sur la croix, je m'attendais a ce que l'input disparaissent (un peu comme une modale finalement), probablement parce que la croix est très loin du texte qu'elle efface. Il n'y a pas cet effet ça en mode desktop (je m'attends a effacer l'input). A voir si d'autres ont ce même réflexe…

Sinon, avec l'ajout de menus sur `master`, le rebase risque de casser un peu le design sur desktop / petit écran. A vérifier.

2020-11-26 07:18 UTC, jibidus requested changes

2020-11-26 07:18 UTC, jibidus commented on site/themes/sogilis/static/js/scripts.js
> +    this.noResultElement.innerHTML = 'No results found.';
```suggestion
    this.noResultElement.innerHTML = 'Aucun résultat trouvé.
```

Vu que l'interface du blog est en français.

2020-11-26 07:18 UTC, jibidus commented on site/themes/sogilis/static/js/scripts.js
> +        <input type="search" id="search-input" class="search-bar__input" placeholder="Search...">
```suggestion
        <input type="search" id="search-input" class="search-bar__input" placeholder="Rechercher…">
```

2020-11-30 09:17 UTC, bdumas1 commented
> J'ai testé sur [app.lambdatest.com](app.lambdatest.com) (1h gratuit par mois) avec iOS, voila ce que j'ai trouvé :
> 
> * Lorsqu'on click sur la loupe, le focus n'est pas mis sur l'input, le clavier virtuel n'apparait donc pas tout de suite
> * [complètement subjectif] Lorsqu'on valide la recherche l'input de recherche reste affiché. Ca fait bizarre je trouve, peut-être manque-t-il juste un peu de marge pour éloigner les résultats du champ de recherche, ce qui posera un problème si le champ de recherche est retiré (en clickant sur la loupe), puisqu'on aura alors une très grosse marge entre le "menu" et les résultats. Idée : mettre le champ de recherche sur la ligne de "menu", comme sur desktop finalement ?
> * Lorsque j'ai clické sur la croix, je m'attendais a ce que l'input disparaissent (un peu comme une modale finalement), probablement parce que la croix est très loin du texte qu'elle efface. Il n'y a pas cet effet ça en mode desktop (je m'attends a effacer l'input). A voir si d'autres ont ce même réflexe…
> 
> Sinon, avec l'ajout de menus sur `master`, le rebase risque de casser un peu le design sur desktop / petit écran. A vérifier.

- Corrigé.
- Je peux augmenter la taille oui, de toute façon si on re-click sur la loupe alors que le champ était ouvert, tout se ferme (même les résultats).
- La c'est le comportement d'un input de type `search` sur mobile, c'est assez courant aujourd'hui sur le web je dirais, je l'ai vu plusieurs fois cette croix qui clear le champ... Tous les navigateurs moderne l’interprète ainsi, à voir si c'est vraiment gênant si on peut enlever ce comportement.

Oui je vais avoir un rebase à faire, ça c'est sûr. Je m'en occupe.

2021-01-06 12:53 UTC, jibidus commented
Petit bug graphique sur desktop, petit écran (800px de large), sur Chrome et Safari :
<img width="950" alt="image" src="https://user-images.githubusercontent.com/7377177/103770558-7feab680-5026-11eb-9c3a-5580866dfa7d.png">

2021-01-06 12:57 UTC, jibidus commented
[Pas bloquant] Je n'ai plus de croix en mode mobile (testé sur Safari / iPhone 11).

2021-01-06 13:25 UTC, jibidus approved these changes

2021-01-06 14:11 UTC, merged